name: CookieCore
main: me.cookie.cookiecore.CookieCore
version: 1.0
description: Core for SemiVanilla plugins
api-version: 1.18
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib:1.6.0'
  - 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0'
commands:
  skipdialogue:
    permission: cookiecore.dialogue.skip
    description: Command that skips current dialogue (personal dialogue).
    usage: /skipdialogue

permissions:
  semicore.dialogue.skip:
    description: Permission to allow of skipping dialogue (personal dialogue).
    default: op